ci: if

diff --git a/.github/workflows/checkout-without-persistcredentials.yaml b/.github/workflows/checkout-without-persistcredentials.yaml
--- a/.github/workflows/checkout-without-persistcredentials.yaml
+++ b/.github/workflows/checkout-without-persistcredentials.yaml
@@ -15,8 +15,14 @@ jobs:
           # default is true. Set to false to avoid persisting the token in git config.
           persist-credentials: false
 
-      - name: fetch default branch
-        run: git fetch ${{ github.event.repository.default_branch }}
+      - name: ls remote should fail
+        run: |
+          if ! git ls-remote origin; then
+            echo "✔️ ls-remote failed as expected"
+          else
+            echo "❌ ls-remote succeeded unexpectedly"
+            exit 1
+          fi
 
       # If you need to do git operations, you need to set git remote again
       - name: set git remote
@@ -26,7 +32,7 @@ jobs:
           git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
           git config user.name  "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-      - name: fetch default branch
+      - name: ls remove should work
         run: git fetch ${{ github.event.repository.default_branch }}
 
       # Delete git config to avoid affecting other steps
