fix: use fetch

diff --git a/.github/workflows/checkout-without-persistcredentials.yaml b/.github/workflows/checkout-without-persistcredentials.yaml
--- a/.github/workflows/checkout-without-persistcredentials.yaml
+++ b/.github/workflows/checkout-without-persistcredentials.yaml
@@ -15,12 +15,12 @@ jobs:
           # default is true. Set to false to avoid persisting the token in git config.
           persist-credentials: false
 
-      - name: ls remote should fail
+      - name: fetch default branch should fail
         run: |
-          if ! git ls-remote origin; then
-            echo "✔️ ls-remote failed as expected"
+          if ! git fetch ${{ github.event.repository.default_branch }}; then
+            echo "✔️ fetch failed as expected"
           else
-            echo "❌ ls-remote succeeded unexpectedly"
+            echo "❌ fetch succeeded unexpectedly"
             exit 1
           fi
 
@@ -32,7 +32,7 @@ jobs:
           git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
           git config user.name  "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-      - name: ls remove should work
+      - name: fetch default branch should work
         run: git fetch ${{ github.event.repository.default_branch }}
 
       # Delete git config to avoid affecting other steps
