chore: change permission check

diff --git a/.github/workflows/checkout-without-persistcredentials.yaml b/.github/workflows/checkout-without-persistcredentials.yaml
--- a/.github/workflows/checkout-without-persistcredentials.yaml
+++ b/.github/workflows/checkout-without-persistcredentials.yaml
@@ -15,12 +15,16 @@ jobs:
           # default is true. Set to false to avoid persisting the token in git config.
           persist-credentials: false
 
-      - name: fetch head ref should fail
+      - name: tag setup
+        run: git tag test-auth-checkout
+
+      - name: verify credentials are not persisted
         run: |
-          if ! git fetch ${{ github.head.ref }}; then
-            echo "✔️ fetch failed as expected"
+          if ! git push origin test-auth-checkout; then
+            echo "✔️ push tag failed as expected due to missing credentials"
           else
-            echo "❌ fetch succeeded unexpectedly"
+            echo "❌ push tag succeeded unexpectedly, credentials were persisted"
+            git push --delete origin test-auth-checkout
             exit 1
           fi
 
@@ -32,8 +36,13 @@ jobs:
           git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
           git config user.name  "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-      - name: fetch head ref should work
-        run: git fetch ${{ github.head.ref }}
+
+      - name: Push and delete test tag to confirm auth
+        run: |
+          git push origin test-auth-checkout
+          git push --delete origin test-auth-checkout
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       # Delete git config to avoid affecting other steps
       - name: Remove git config
