chore: indent

diff --git a/.github/workflows/checkout-without-persistcredentials.yaml b/.github/workflows/checkout-without-persistcredentials.yaml
--- a/.github/workflows/checkout-without-persistcredentials.yaml
+++ b/.github/workflows/checkout-without-persistcredentials.yaml
@@ -1,53 +1,53 @@
 name: checkout without persist-credentials
 on:
-    pull_request:
-        branches: ["main"]
+  pull_request:
+    branches: ["main"]
 
 jobs:
-    checkout:
-        permissions:
-            contents: write
-        runs-on: ubuntu-24.04
-        timeout-minutes: 10
-        steps:
-            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-              with:
-                  # default is true. Set to false to avoid persisting the token in git config.
-                  persist-credentials: false
+  checkout:
+    permissions:
+      contents: write
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    steps:
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          # default is true. Set to false to avoid persisting the token in git config.
+          persist-credentials: false
 
-            - name: tag setup
-              run: git tag test-auth-checkout
+      - name: tag setup
+        run: git tag test-auth-checkout
 
-            - name: verify credentials are not persisted
-              run: |
-                  if ! git push origin test-auth-checkout; then
-                    echo "✔️ push tag failed as expected due to missing credentials"
-                  else
-                    echo "❌ push tag succeeded unexpectedly, credentials were persisted"
-                    git push --delete origin test-auth-checkout
-                    exit 1
-                  fi
+      - name: verify credentials are not persisted
+        run: |
+          if ! git push origin test-auth-checkout; then
+            echo "✔️ push tag failed as expected due to missing credentials"
+          else
+            echo "❌ push tag succeeded unexpectedly, credentials were persisted"
+            git push --delete origin test-auth-checkout
+            exit 1
+          fi
 
-            # If you need to do git operations, you need to set git remote again
-            - name: set git remote
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              run: |
-                  git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
-                  git config user.name  "github-actions[bot]"
-                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      # If you need to do git operations, you need to set git remote again
+      - name: set git remote
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
+          git config user.name  "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-            - name: Push and delete test tag to confirm auth
-              run: |
-                  git push origin test-auth-checkout
-                  git push --delete origin test-auth-checkout
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Push and delete test tag to confirm auth
+        run: |
+          git push origin test-auth-checkout
+          git push --delete origin test-auth-checkout
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-            # Delete git config to avoid affecting other steps
-            - name: Remove git config
-              if: always()
-              run: |
-                  git remote rm origin
-                  git config --unset user.email
-                  git config --unset user.name
+      # Delete git config to avoid affecting other steps
+      - name: Remove git config
+        if: always()
+        run: |
+          git remote rm origin
+          git config --unset user.email
+          git config --unset user.name
diff --git a/.github/workflows/continue-on-error.yaml b/.github/workflows/continue-on-error.yaml
--- a/.github/workflows/continue-on-error.yaml
+++ b/.github/workflows/continue-on-error.yaml
@@ -1,24 +1,24 @@
 name: "continue on error"
 on:
-    workflow_dispatch:
-    push:
-        branches: ["main"]
+  workflow_dispatch:
+  push:
+    branches: ["main"]
 
 jobs:
-    continue-on-error:
-        permissions:
-            contents: read
-        runs-on: ubuntu-24.04
-        timeout-minutes: 3
-        steps:
-            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-              with:
-                  persist-credentials: false
-            - run: exit 1
-              continue-on-error: true
-            - run: exit 1
-              continue-on-error: true
-            - run: echo success
-            # never call failure(), as continue-on-error treat step error as success.
-            - if: ${{ failure() }}
-              run: echo error happen
+  continue-on-error:
+    permissions:
+      contents: read
+    runs-on: ubuntu-24.04
+    timeout-minutes: 3
+    steps:
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          persist-credentials: false
+      - run: exit 1
+        continue-on-error: true
+      - run: exit 1
+        continue-on-error: true
+      - run: echo success
+      # never call failure(), as continue-on-error treat step error as success.
+      - if: ${{ failure() }}
+        run: echo error happen
diff --git a/.github/workflows/crlf-checker.yaml b/.github/workflows/crlf-checker.yaml
--- a/.github/workflows/crlf-checker.yaml
+++ b/.github/workflows/crlf-checker.yaml
@@ -1,79 +1,79 @@
 # Description: Detect if PUSH or PR includes End of Line `CRLF` files.
 name: crlf checker
 on:
-    workflow_dispatch:
-    pull_request:
-        branches: ["main"]
-    push:
-        branches: ["main"]
+  workflow_dispatch:
+  pull_request:
+    branches: ["main"]
+  push:
+    branches: ["main"]
 
 jobs:
-    check:
-        permissions:
-            contents: read
-        runs-on: ubuntu-24.04
-        timeout-minutes: 5
-        steps:
-            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-              with:
-                  fetch-depth: 2 # detect on push
-                  persist-credentials: false
-            # you can specify which file to detect.
-            - id: changed-files
-              uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
-              with:
-                  list-files: csv # default 'none'. Disables listing of matching files.
-                  filters: |
-                      foo:
-                        - my-file.txt
-                        - test.txt
-                        - new.txt
-                        - test_directory
-                        - \.foo$
-                        - \.sh$
-                        - .(png|jpeg)$
-                        - .(cs|csproj)$
-                        - ^(mynewfile|custom)
-                        - .yaml$
-            # do not use space in file name.
-            #   OK: foo.bar
-            #   NG: foo 1.bar
-            - name: Detect CRLF
-              run: |
-                  err=false
-                  for file in $(echo "${{ steps.changed-files.outputs.foo_files }}" | sed -e "s/,/ /g"); do
-                    if file "${file}" | grep CRLF > /dev/null; then
-                      err=true
-                      echo "'${file}' detected as CRLF."
-                      if [[ "${crlf_files}" != "" ]]; then crlf_files="${crlf_files}$IFS"; fi
-                      crlf_files="${crlf_files} ${file}"
-                    fi
-                  done
+  check:
+    permissions:
+      contents: read
+    runs-on: ubuntu-24.04
+    timeout-minutes: 5
+    steps:
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          fetch-depth: 2 # detect on push
+          persist-credentials: false
+      # you can specify which file to detect.
+      - id: changed-files
+        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
+        with:
+          list-files: csv # default 'none'. Disables listing of matching files.
+          filters: |
+            foo:
+              - my-file.txt
+              - test.txt
+              - new.txt
+              - test_directory
+              - \.foo$
+              - \.sh$
+              - .(png|jpeg)$
+              - .(cs|csproj)$
+              - ^(mynewfile|custom)
+              - .yaml$
+      # do not use space in file name.
+      #   OK: foo.bar
+      #   NG: foo 1.bar
+      - name: Detect CRLF
+        run: |
+          err=false
+          for file in $(echo "${{ steps.changed-files.outputs.foo_files }}" | sed -e "s/,/ /g"); do
+            if file "${file}" | grep CRLF > /dev/null; then
+              err=true
+              echo "'${file}' detected as CRLF."
+              if [[ "${crlf_files}" != "" ]]; then crlf_files="${crlf_files}$IFS"; fi
+              crlf_files="${crlf_files} ${file}"
+            fi
+          done
 
-                  if [[ "${err}" == "true" ]]; then
-                    {
-                      echo "CRLF_FILES<<EOF"
-                      echo "${crlf_files}"
-                      echo "EOF"
-                    } >> "$GITHUB_ENV"
-                  fi
-            # comment to PR for CRLF files.
-            - if: ${{ github.event_name == 'pull_request' && env.CRLF_FILES != '' }}
-              name: Comment PR
-              run: |
-                  cat << 'EOF' > pr_comment.md
-                    Workflow [${{ env.GITHUB_ACTIONS_RUN_URL }}) found CRLF files as follows.
+          if [[ "${err}" == "true" ]]; then
+            {
+              echo "CRLF_FILES<<EOF"
+              echo "${crlf_files}"
+              echo "EOF"
+            } >> "$GITHUB_ENV"
+          fi
+      # comment to PR for CRLF files.
+      - if: ${{ github.event_name == 'pull_request' && env.CRLF_FILES != '' }}
+        name: Comment PR
+        run: |
+          cat << 'EOF' > pr_comment.md
+            Workflow [${{ env.GITHUB_ACTIONS_RUN_URL }}) found CRLF files as follows.
 
-                    ```
-                    ${{ env.CRLF_FILES }}
-                    ```
+            ```
+            ${{ env.CRLF_FILES }}
+            ```
 
-                  EOF
-              env:
-                  GITHUB_ACTIONS_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-                  GH_REPO: ${{ github.repository }}
-                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            # Fail action if CRLF file found.
-            - if: ${{ env.CRLF_FILES != '' }}
-              name: Exit action if detected
-              run: exit 1
+          EOF
+        env:
+          GITHUB_ACTIONS_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+          GH_REPO: ${{ github.repository }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # Fail action if CRLF file found.
+      - if: ${{ env.CRLF_FILES != '' }}
+        name: Exit action if detected
+        run: exit 1
